In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
# importing datasets
df = pd.read_csv("..\dataset\Banglore_traffic_Dataset_raw.csv")
df.tail()

Date        Area Name Road/Intersection Name  Traffic Volume  \
8931  2024-08-09  Electronic City             Hosur Road           11387   
8932  2024-08-09        M.G. Road         Trinity Circle           36477   
8933  2024-08-09        M.G. Road     Anil Kumble Circle           42822   
8934  2024-08-09        Jayanagar       South End Circle           20540   
8935  2024-08-09     Yeshwanthpur    Yeshwanthpur Circle           14705   

      Average Speed  Travel Time Index  Congestion Level  \
8931      23.440276           1.262384         35.871483   
8932      45.168429           1.500000        100.000000   
8933      22.028609           1.500000        100.000000   
8934      52.254798           1.020520         72.639152   
8935      31.128967           1.048720         43.409821   

      Road Capacity Utilization  Incident Reports  Environmental Impact  \
8931                  57.354487                 1                72.774   
8932                 100.000000                 3               122.954   
8933                 100.000000                 1               135.644   
8934                  97.845527                 2                91.080   
8935                  77.734621                 1                79.410   

      Public Transport Usage  Traffic Signal Compliance  Parking Usage  \
8931               21.523289                  83.530352      97.898279   
8932               29.822312                  60.738488      60.355967   
8933               43.185905                  85.321627      61.333731   
8934               44.416043                  89.586947      79.197198   
8935               26.616725                  80.778753      60.602672   

      Pedestrian and Cyclist Count Weather Conditions  \
8931                           211                Fog   
8932                            95              Clear   
8933                           110              Clear   
8934                            94              Clear   
8935                           201               Rain   

     Roadwork and Construction Activity  
8931                                 No  
8932                                 No  
8933                                 No  
8934                                 No  
8935                                 No

In [3]:
# copying the original dataset file
df_copy = df.copy()
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8936 entries, 0 to 8935
Data columns (total 16 columns):
 #   Column                              Non-Null Count  Dtype  
---  ------                              --------------  -----  
 0   Date                                8936 non-null   object 
 1   Area Name                           8936 non-null   object 
 2   Road/Intersection Name              8936 non-null   object 
 3   Traffic Volume                      8936 non-null   int64  
 4   Average Speed                       8936 non-null   float64
 5   Travel Time Index                   8936 non-null   float64
 6   Congestion Level                    8936 non-null   float64
 7   Road Capacity Utilization           8936 non-null   float64
 8   Incident Reports                    8936 non-null   int64  
 9   Environmental Impact                8936 non-null   float64
 10  Public Transport Usage              8936 non-null   float64
 11  Traffic Signal Compliance           8936 no

In [4]:
df_copy.describe()

Traffic Volume  Average Speed  Travel Time Index  Congestion Level  \
count     8936.000000    8936.000000        8936.000000       8936.000000   
mean     29236.048120      39.447427           1.375554         80.818041   
std      13001.808801      10.707244           0.165319         23.533182   
min       4233.000000      20.000000           1.000039          5.160279   
25%      19413.000000      31.775825           1.242459         64.292905   
50%      27600.000000      39.199368           1.500000         92.389018   
75%      38058.500000      46.644517           1.500000        100.000000   
max      72039.000000      89.790843           1.500000        100.000000   

       Road Capacity Utilization  Incident Reports  Environmental Impact  \
count                8936.000000       8936.000000           8936.000000   
mean                   92.029215          1.570389            108.472096   
std                    16.583341          1.420047             26.003618   
min                    18.739771          0.000000             58.466000   
25%                    97.354990          0.000000             88.826000   
50%                   100.000000          1.000000            105.200000   
75%                   100.000000          2.000000            126.117000   
max                   100.000000         10.000000            194.078000   

       Public Transport Usage  Traffic Signal Compliance  Parking Usage  \
count             8936.000000                8936.000000    8936.000000   
mean                45.086651                  79.950243      75.155597   
std                 20.208460                  11.585006      14.409394   
min                 10.006853                  60.003933      50.020411   
25%                 27.341191                  69.828270      62.545895   
50%                 45.170684                  79.992773      75.317610   
75%                 62.426485                  89.957358      87.518589   
max                 79.979744                  99.993652      99.995049   

       Pedestrian and Cyclist Count  
count                   8936.000000  
mean                     114.533348  
std                       36.812573  
min                       66.000000  
25%                       94.000000  
50%                      102.000000  
75%                      111.000000  
max                      243.000000

In [5]:
# checking for null values
missing_count = df_copy.isnull().sum().sort_values(ascending = False)
missing_count

Date                                  0
Area Name                             0
Road/Intersection Name                0
Traffic Volume                        0
Average Speed                         0
Travel Time Index                     0
Congestion Level                      0
Road Capacity Utilization             0
Incident Reports                      0
Environmental Impact                  0
Public Transport Usage                0
Traffic Signal Compliance             0
Parking Usage                         0
Pedestrian and Cyclist Count          0
Weather Conditions                    0
Roadwork and Construction Activity    0
dtype: int64

In [6]:
# checking for NaN values
find_na = df_copy.isna().sum()
find_na

Date                                  0
Area Name                             0
Road/Intersection Name                0
Traffic Volume                        0
Average Speed                         0
Travel Time Index                     0
Congestion Level                      0
Road Capacity Utilization             0
Incident Reports                      0
Environmental Impact                  0
Public Transport Usage                0
Traffic Signal Compliance             0
Parking Usage                         0
Pedestrian and Cyclist Count          0
Weather Conditions                    0
Roadwork and Construction Activity    0
dtype: int64

In [7]:
# checking index values are unique or not
df_copy.index.is_unique

True

In [8]:
# Checking for any duplicate values
duplicate_values = df_copy.duplicated().sum()
duplicate_values

np.int64(0)

In [9]:
# Changing the of 'date' from 'object' to 'datetime' object
df_copy['Date'] = pd.to_datetime(df_copy['Date'])
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8936 entries, 0 to 8935
Data columns (total 16 columns):
 #   Column                              Non-Null Count  Dtype         
---  ------                              --------------  -----         
 0   Date                                8936 non-null   datetime64[ns]
 1   Area Name                           8936 non-null   object        
 2   Road/Intersection Name              8936 non-null   object        
 3   Traffic Volume                      8936 non-null   int64         
 4   Average Speed                       8936 non-null   float64       
 5   Travel Time Index                   8936 non-null   float64       
 6   Congestion Level                    8936 non-null   float64       
 7   Road Capacity Utilization           8936 non-null   float64       
 8   Incident Reports                    8936 non-null   int64         
 9   Environmental Impact                8936 non-null   float64       
 10  Public Transport Usage  

In [10]:
df_copy['Weather Conditions'].unique()

array(['Clear', 'Overcast', 'Fog', 'Rain', 'Windy'], dtype=object)

In [11]:
df_copy['Area Name'].unique()

array(['Indiranagar', 'Whitefield', 'Koramangala', 'M.G. Road',
       'Jayanagar', 'Hebbal', 'Yeshwanthpur', 'Electronic City'],
      dtype=object)

In [12]:
df_copy['Road/Intersection Name'].unique()

array(['100 Feet Road', 'CMH Road', 'Marathahalli Bridge',
       'Sony World Junction', 'Sarjapur Road', 'Trinity Circle',
       'Anil Kumble Circle', 'Jayanagar 4th Block', 'South End Circle',
       'Hebbal Flyover', 'Ballari Road', 'Yeshwanthpur Circle',
       'Tumkur Road', 'ITPL Main Road', 'Silk Board Junction',
       'Hosur Road'], dtype=object)

In [13]:
df_copy['Roadwork and Construction Activity'].unique()

array(['No', 'Yes'], dtype=object)

In [14]:
# Creating new columns from date to use this is future to create the dashboard
df_copy['Day of Week'] = df_copy['Date'].dt.day_of_week
df_copy['Is Weekend'] = (df_copy['Day of Week'] >= 5).astype(int)
df_copy['Day Name'] = df_copy['Date'].dt.day_name()
df_copy['Month'] = df_copy['Date'].dt.month
df_copy['Year'] = df_copy['Date'].dt.year

In [15]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8936 entries, 0 to 8935
Data columns (total 21 columns):
 #   Column                              Non-Null Count  Dtype         
---  ------                              --------------  -----         
 0   Date                                8936 non-null   datetime64[ns]
 1   Area Name                           8936 non-null   object        
 2   Road/Intersection Name              8936 non-null   object        
 3   Traffic Volume                      8936 non-null   int64         
 4   Average Speed                       8936 non-null   float64       
 5   Travel Time Index                   8936 non-null   float64       
 6   Congestion Level                    8936 non-null   float64       
 7   Road Capacity Utilization           8936 non-null   float64       
 8   Incident Reports                    8936 non-null   int64         
 9   Environmental Impact                8936 non-null   float64       
 10  Public Transport Usage  

In [16]:
print(df_copy['Day of Week'].unique())

[5 6 0 1 2 3 4]


In [17]:
print(df_copy['Is Weekend'].unique())

[1 0]


In [18]:
print(df_copy['Day Name'].unique())

['Saturday' 'Sunday' 'Monday' 'Tuesday' 'Wednesday' 'Thursday' 'Friday']


In [19]:
print(df_copy['Month'].unique())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [20]:
print(df_copy['Year'].unique())

[2022 2023 2024]


In [21]:
df_copy.head()

Date    Area Name Road/Intersection Name  Traffic Volume  \
0 2022-01-01  Indiranagar          100 Feet Road           50590   
1 2022-01-01  Indiranagar               CMH Road           30825   
2 2022-01-01   Whitefield    Marathahalli Bridge            7399   
3 2022-01-01  Koramangala    Sony World Junction           60874   
4 2022-01-01  Koramangala          Sarjapur Road           57292   

   Average Speed  Travel Time Index  Congestion Level  \
0      50.230299           1.500000        100.000000   
1      29.377125           1.500000        100.000000   
2      54.474398           1.039069         28.347994   
3      43.817610           1.500000        100.000000   
4      41.116763           1.500000        100.000000   

   Road Capacity Utilization  Incident Reports  Environmental Impact  ...  \
0                 100.000000                 0               151.180  ...   
1                 100.000000                 1               111.650  ...   
2                  36.396525                 0                64.798  ...   
3                 100.000000                 1               171.748  ...   
4                 100.000000                 3               164.584  ...   

   Traffic Signal Compliance  Parking Usage  Pedestrian and Cyclist Count  \
0                  84.044600      85.403629                           111   
1                  91.407038      59.983689                           100   
2                  61.375541      95.466020                           189   
3                  75.547092      63.567452                           111   
4                  64.634762      93.155171                           104   

   Weather Conditions Roadwork and Construction Activity Day of Week  \
0               Clear                                 No           5   
1               Clear                                 No           5   
2               Clear                                 No           5   
3               Clear                                 No           5   
4               Clear                                 No           5   

   Is Weekend  Day Name Month  Year  
0           1  Saturday     1  2022  
1           1  Saturday     1  2022  
2           1  Saturday     1  2022  
3           1  Saturday     1  2022  
4           1  Saturday     1  2022  

[5 rows x 21 columns]

In [22]:
# Exporting the cleaned and processed data
df_copy.to_csv("..\dataset\processed_dataset.csv", index = False)